services:
  ml:
    build: .
    container_name: flight-price-ml
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root